on: 
  push:
    branches: ['master']
  
name: Laravel CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
 
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: usertest
          MYSQL_PASSWORD: 
          MYSQL_DATABASE: testdatabase
          MYSQL_ROOT_PASSWORD: testing
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Update composer dependencies
      run: composer update

    - name: Install dependencies
      run: composer install --no-interaction --no-suggest --ignore-platform-reqs
    
    - name: Boot Laravel application
      run: |
        php -r "file_exists('.env') || copy('.env.example', '.env');"
        php artisan key:generate
        php artisan --version

    - name: Execute migrations
      env:
        DB_CONNECTION: mysql
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
        DB_USER: usertest
        DB_PASSWORD: testing
      run: |
        php artisan migrate