on: 
  push:
    branches: ['master']
  
name: Laravel CI
jobs:
  laravel-biuld:
    runs-on: ubuntu-latest
    # env:
    #   DB_DATABASE: test_db
    #   DB_USER: root
    #   DB_PASSWORD: root
    # services:
    #   mysql:
    #     image: mysql:8.0
    #     env:
            # DB_DATABASE: test_db
            # DB_USER: root
            # DB_PASSWORD: root
    #     ports:
    #       - 33306:3306
    #     options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Update composer dependencies
      run: composer update

    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
    - name: Install dependencies
      run: composer install --no-interaction --no-suggest --ignore-platform-reqs
    
    - name: Boot Laravel application
      run: |
        php -r "file_exists('.env') || copy('.env.example', '.env');"
        php artisan key:generate
        php artisan --version

    - name: Execute migrations
      run: |
        php artisan migrate