on: 
  push:
    branches: ['master']
  
name: Laravel CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
 
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: usertest
          MYSQL_PASSWORD: 
          MYSQL_DATABASE: testdatabase
          MYSQL_ROOT_PASSWORD: testin
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install dependencies
      run: |
        php --version
        composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
        chmod -R 777 storage bootstrap/cache

    - name: Boot Laravel application
      run: |
        php -r "file_exists('.env') || copy('.env.example', '.env');"
        php artisan key:generate
        php artisan --version

    - name: Execute PHPUnit tests
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: 172.18.0.1
        DB_PORT: 3306
        DB_USER: testdatabase
        DB_PASSWORD: testin
      run: |
        php artisan migrate:fresh --seed
        ./vendor/bin/phpunit 